export const CREATE_USER_REQUEST = '@@users/CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = '@@users/CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = '@@users/CREATE_USER_FAILURE'

export const UPDATE_PROFILE_INFO_REQUEST = '@@users/UPDATE_PROFILE_INFO_REQUEST'
export const UPDATE_PROFILE_INFO_SUCCESS = '@@users/UPDATE_PROFILE_INFO_SUCCESS'
export const UPDATE_PROFILE_INFO_FAILURE = '@@users/UPDATE_PROFILE_INFO_FAILURE'

export const GET_PROFILE_INFO_REQUEST = '@@users/GET_PROFILE_INFO_REQUEST'
export const GET_PROFILE_INFO_SUCCESS = '@@users/GET_PROFILE_INFO_SUCCESS'
export const GET_PROFILE_INFO_FAILURE = '@@users/GET_PROFILE_INFO_FAILURE'

export const CREATE_PET_REQUEST = '@@pets/CREATE_PET_REQUEST'
export const CREATE_PET_SUCCESS = '@@pets/CREATE_PET_SUCCESS'
export const CREATE_PET_FAILURE = '@@pets/CREATE_PET_FAILURE'

export const UPDATE_PET_INFO_REQUEST = '@@pets/UPDATE_PET_INFO_REQUEST'
export const UPDATE_PET_INFO_SUCCESS = '@@pets/UPDATE_PET_INFO_SUCCESS'
export const UPDATE_PET_INFO_FAILURE = '@@pets/UPDATE_PET_INFO_FAILURE'

export const DELETE_PET_REQUEST = '@@pets/DELETE_PET_REQUEST'
export const DELETE_PET_SUCCESS = '@@pets/DELETE_PET_SUCCESS'
export const DELETE_PET_FAILURE = '@@pets/DELETE_PET_FAILURE'

export const GET_PETS_LIST_REQUEST = '@@pets/GET_PETS_LIST_REQUEST'
export const GET_PETS_LIST_SUCCESS = '@@pets/GET_PETS_LIST_SUCCESS'
export const GET_PETS_LIST_FAILURE = '@@pets/GET_PETS_LIST_FAILURE'

export const GET_PET_INFO_REQUEST = '@@pets/GET_PET_INFO_REQUEST'
export const GET_PET_INFO_SUCCESS = '@@pets/GET_PET_INFO_SUCCESS'
export const GET_PET_INFO_FAILURE = '@@pets/GET_PET_INFO_FAILURE'

export const CREATE_VET_PROCEDURE_REQUEST = '@@procs/CREATE_VET_PROCEDURE_REQUEST'
export const CREATE_VET_PROCEDURE_SUCCESS = '@@procs/CREATE_VET_PROCEDURE_SUCCESS'
export const CREATE_VET_PROCEDURE_FAILURE = '@@procs/CREATE_VET_PROCEDURE_FAILURE'

export const GET_VET_PROCEDURES_REQUEST = '@@procs/GET_VET_PROCEDURES_REQUEST'
export const GET_VET_PROCEDURES_SUCCESS = '@@procs/GET_VET_PROCEDURES_SUCCESS'
export const GET_VET_PROCEDURES_FAILURE = '@@procs/GET_VET_PROCEDURES_FAILURE'

export const CREATE_OWNER_PROCEDURE_REQUEST = '@@procs/CREATE_OWNER_PROCEDURE_REQUEST'
export const CREATE_OWNER_PROCEDURE_SUCCESS = '@@procs/CREATE_OWNER_PROCEDURE_SUCCESS'
export const CREATE_OWNER_PROCEDURE_FAILURE = '@@procs/CREATE_OWNER_PROCEDURE_FAILURE'

export const GET_OWNER_PROCEDURES_REQUEST = '@@procs/GET_OWNER_PROCEDURES_REQUEST'
export const GET_OWNER_PROCEDURES_SUCCESS = '@@procs/GET_OWNER_PROCEDURES_SUCCESS'
export const GET_OWNER_PROCEDURES_FAILURE = '@@procs/GET_OWNER_PROCEDURES_FAILURE'

export const GET_PATIENTS_LIST_REQUEST = '@@patients/GET_PATIENTS_LIST_REQUEST'
export const GET_PATIENTS_LIST_SUCCESS = '@@patients/GET_PATIENTS_LIST_SUCCESS'
export const GET_PATIENTS_LIST_FAILURE = '@@patients/GET_PATIENTS_LIST_FAILURE'

export const GET_SCHEDULE_REQUEST = '@@schedule/GET_SCHEDULE_REQUEST'
export const GET_SCHEDULE_SUCCESS = '@@schedule/GET_SCHEDULE_SUCCESS'
export const GET_SCHEDULE_FAILURE = '@@schedule/GET_SCHEDULE_FAILURE'

export const CREATE_SCHEDULE_REQUEST = '@@schedule/CREATE_SCHEDULE_REQUEST'
export const CREATE_SCHEDULE_SUCCESS = '@@schedule/CREATE_SCHEDULE_SUCCESS'
export const CREATE_SCHEDULE_FAILURE = '@@schedule/CREATE_SCHEDULE_FAILURE'

export const GET_SEARCH_PETS_REQUEST = '@@search/GET_SEARCH_PETS_REQUEST'
export const GET_SEARCH_PETS_SUCCESS = '@@search/GET_SEARCH_PETS_SUCCESS'
export const GET_SEARCH_PETS_FAILURE = '@@search/GET_SEARCH_PETS_FAILURE'

export const GET_SEARCH_VET_PROCS_REQUEST = '@@search/GET_SEARCH_VET_PROCS_REQUEST'
export const GET_SEARCH_VET_PROCS_SUCCESS = '@@search/GET_SEARCH_VET_PROCS_SUCCESS'
export const GET_SEARCH_VET_PROCS_FAILURE = '@@search/GET_SEARCH_VET_PROCS_FAILURE'

export const GET_SEARCH_OWNER_PROCS_REQUEST = '@@search/GET_SEARCH_OWNER_PROCS_REQUEST'
export const GET_SEARCH_OWNER_PROCS_SUCCESS = '@@search/GET_SEARCH_OWNER_PROCS_SUCCESS'
export const GET_SEARCH_OWNER_PROCS_FAILURE = '@@search/GET_SEARCH_OWNER_PROCS_FAILURE'
